repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Autofixes trailing whitespace
      - id: end-of-file-fixer # Autofixes missing newline at EOF
      - id: check-yaml # Only checks for YAML syntax issues
      - id: check-added-large-files # Only reports large files

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black # Autofixes Python formatting issues
        files: \.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8 # Reports Python style/quality issues (no autofix)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy # Reports Python type issues (no autofix)
